# Generated by Django 5.0.6 on 2025-03-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
