# Generated by Django 5.0.6 on 2025-03-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_vendorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
